In [25]:
import numpy as np

In [27]:
def compute_reciprocals(values):
    output = np.empty(len(values))
    for i in range(len(values)):
        output[i] = 1.0 / values[i]
    return output


In [28]:
big_array = np.random.randint(1, 100, size=1000000)

# jupyter maing function (timeit)
%timeit compute_reciprocals(big_array)


3.77 s ± 86.9 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [31]:
np.random.seed(1)
arr1= np.random.randint(10 , size=5)
arr= np.random.randint(10 , size=5)


In [34]:
"""
UFuncs: Absolute Value
"""

x = np.array([-2,-1,0,1,2])
print(np.abs(x))

x=np.array([3-4j, 4-3j, 2+0j ,0+1j])
print(np.abs(x))

[2 1 0 1 2]
[5. 5. 2. 1.]


In [37]:
theta = np.linspace(0 , np.pi , 3)

print(theta)
print(np.sin(theta))
print(np.cos(theta))
print(np.tan(theta))

x = np.linspace(0 , 100 , 11)
print(x)

[0.         1.57079633 3.14159265]
[0.0000000e+00 1.0000000e+00 1.2246468e-16]
[ 1.000000e+00  6.123234e-17 -1.000000e+00]
[ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]
[  0.  10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]


In [41]:
x=np.arange(1,5)
print(x)

aggr=np.add.reduce(x)
print(aggr)

aggr=np.multiply.reduce(x)
print(aggr)

[1 2 3 4]
10
24


In [44]:
accum = np.add.accumulate(x)
print(accum)

accum= np.multiply.accumulate(x)
print(accum)

[ 1  3  6 10]
[ 1  2  6 24]


In [49]:
np.random.seed(3)
arr = np.random.rand(1000000) # rand() : creadte 0~1 real numbers 0과 1 사이의 난수를 생성해줌

print(arr)
print("sum =",np.sum(arr))


[0.5507979  0.70814782 0.29090474 ... 0.93033748 0.80429816 0.47400579]
sum = 500422.19897015305


In [51]:
%timeit sum(arr)

137 ms ± 5.42 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [53]:
%timeit np.sum(arr)

2.43 ms ± 219 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [59]:
print("max =",np.max(arr))
print("min =",np.min(arr))
print("mean =",np.mean(arr))
print("median =",np.median(arr))
print("percentile =", np.percentile(arr, 90))

print(np.any(arr>1))
print(np.all(arr>0)) #range(0,1)

max = 0.9999996367889004
min = 1.5496004267534502e-06
mean = 0.500422198970153
median = 0.5005659265960778
percentile = 0.9001765340710965
False
True


In [64]:
np.random.seed(5)
arr = np.random.randint(10 , size=(3,4))
print(arr)

print(np.sum(arr))

print(np.sum(arr,axis=0))

print(np.sum(arr,axis=1))


[[3 6 6 0]
 [9 8 4 7]
 [0 0 7 1]]
51
[12 14 17  8]
[15 28  8]
